name: FaithBreak
version: '1.3.1'
main: com.faithBreak.FaithBreak
api-version: '1.21'
authors: [CiscoCodes]
commands:
  non-muslim:
    description: Toggle opting out of prayer time kicks and reminders.
    usage: /non-muslim
    permission: faithbreak.nonmuslim
  fb:
    description: FaithBreak commands.
    usage: /fb <lang|kick> [args]
    permission: faithbreak.use
permissions:
  faithbreak.nonmuslim:
    description: Allows players to use the /non-muslim command to opt out of prayer time actions.
    default: true
  faithbreak.use:
    description: Allows access to FaithBreak commands.
    default: true
  faithbreak.admin:
    description: Allows access to FaithBreak admin commands (kick test).
    default: op
